### PR TITLE
update to latest Turing.jl

### PR DESCRIPTION
**Pull request by jClugstor**
## Checklist

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API
  
## Additional context
Update Turing to fix compatibility issues.

### CODE REVIEW

**Comment by jClugstor** [comment]
Tests, pass, but CodeCov doesn't run. I think that's expected because of the CodeCov changes happening?

**Comment by ChrisRackauckas** [comment]
datafit tests don't pass?

**Comment by jClugstor** [comment]
I think they don't run if the Core tests don't completely pass. Since the codecov test didn't pass, the datafit tests never actually ran.

**Comment by jClugstor** [comment]
Should I just get rid of codecov in the CI?

**Comment by ChrisRackauckas** [comment]
It should already be disabled.

**Comment by jClugstor** [comment]
Ok so the datafit tests ran, but they took so long that it canceled out? 
Hmm...

**Comment by jClugstor** [comment]
The tests are getting dt under epsilon and hitting maxiters now, which I can confirm doesn't happen with Turing 0.30. There was just a Turing patch, I'll try that.

**Pull request closed without merging**
