### PR TITLE
try updating

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by jClugstor** [comment]
It looks like a few tests are erroring after updating, not just in datafit. One Sensitivity, one Ensemble, and one Threshold test all fail when tested locally.

**Comment by jClugstor** [comment]
In `_get_sensitivity` there's a line ` prob_func(prob, i, repeat) = remake(prob; p = Pair.(boundkeys, p[:, i]))` does the `remake` still make sense with the update to MTK handling of parameters? The error is related to the initial conditions, maybe we need to supply the default initial conditions to the remake?

**Comment by ChrisRackauckas** [comment]
It does not, it needs to use the SciMLStructures canonicalization

**Comment by ChrisRackauckas** [comment]
Yes

**Pull request merged**
