### PR TITLE
Try updating compats 

### PR DESCRIPTION
**Pull request by jClugstor**
## Checklist

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API

### CODE REVIEW

**Comment by jClugstor** [comment]
All tests except threshold should pass. 
Changes need to be made in some of the intervention functions. Things that are expecting scalars are getting vectors. In one of the tests, `optimal_parameter_intervention_for_reach` is trying to treat a tuple as callable.

**Comment by jClugstor** [comment]
This assumes that the cost function is intended to return a scalar, which should always be true as far as I know. The tuple stuff was because of a weird REPL state that I had where `p` was an array. Maybe if `build_function` ends up returning a tuple we should add an error message saying that the cost function should return a scalar?

There's still one more thing to fix in `prob_violating_threshold`, something to do with SciMLExpectations.

**Comment by ChrisRackauckas** [comment]
Is it not using the latest Integrals.jl?

**Comment by jClugstor** [comment]
My manifest says `version = 4.4.1` which I believe is the latest.

**Comment by jClugstor** [comment]
I just needed to get rid of the `batch = 0`, so it defaults to `batch = nothing` which I think is in line with what was intended anyway.

**Comment by jClugstor** [comment]
Tests pass locally now. Looks like the tests for datafit passed, but there was an issue in code coverage, which caused the core tests to abort.

**Pull request merged**
